name: Onion Classifier CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16-dind
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install requests pytest

    - name: Run Unit Tests
      run: pytest tests/test_unit.py --maxfail=1 --disable-warnings -q

    - name: Run Local Model Test
      run: python local_test.py

    - name: Build Docker Image
      if: success()
      run: |
        docker build -t onion_classifier:latest .

    - name: Run Docker Container for Integration Test
      if: success()
      run: |
        docker run -d --name onion_api -p 8000:8000 onion_classifier:latest
        sleep 5  # wait for API to start
        pytest tests/test_api.py
        docker stop onion_api
        docker rm onion_api

    - name: Push Docker Image
      if: success()
      env:
        DOCKER_USERNAME: ${{ secrets.iharishreddy1713 }}
        DOCKER_PASSWORD: ${{ secrets.Harish123@s }}
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker tag onion_classifier:latest yourdockerhub/onion_classifier:latest
        docker push yourdockerhub/onion_classifier:latest
